-- SKWAD Media Organiser — PostgreSQL baseline schema.
--
-- This is the SQLite schema (migrations 1..13) collapsed into one baseline.
-- A Postgres library is always created fresh — an existing SQLite library is
-- moved across by `skwad-db-migrate`, which copies rows rather than replaying
-- history — so there is nothing for 2..13 to upgrade.
--
-- Dialect notes, so the next person does not have to rediscover them:
--   * SQLite `INTEGER PRIMARY KEY` -> `BIGINT GENERATED BY DEFAULT AS IDENTITY`.
--     "BY DEFAULT" (not "ALWAYS") matters: the data migration inserts explicit
--     ids to preserve every foreign key, then resyncs the sequences.
--   * `REAL` -> `DOUBLE PRECISION`, because every mirrored Rust field is `f64`.
--   * `BLOB` -> `BYTEA` (little-endian f32 vectors, unchanged on the wire).
--   * `COLLATE NOCASE` -> a non-deterministic ICU collation, `nocase`. It gives
--     case-insensitive `=`, `UNIQUE` and grouping with the same semantics as
--     SQLite's, and unlike `citext` an ordinary `$1` text parameter still binds
--     against it — so not one of the call sites that relied on the collation
--     had to change. (`citext` is a distinct type; rust-postgres refuses to
--     send a `&str` for its OID.)
--   * Booleans stay 0/1 `BIGINT` rather than becoming `BOOLEAN`: the repo layer
--     reads them as `i64` and compares them as `= 1` in SQL, and changing the
--     storage type would have meant touching every one of those sites for no
--     behavioural gain.
--   * Timestamps stay `TEXT` holding RFC3339. The whole application passes them
--     as `String` across the Tauri boundary; `timestamptz` would have rippled
--     all the way into the TypeScript layer.
--   * The six `*_assign_stable_id` triggers are gone — a column default of
--     `gen_random_uuid()` does the same job without a statement per insert.

-- SQLite's `COLLATE NOCASE`, in Postgres terms. `deterministic = false` is what
-- makes equality itself case-insensitive rather than only the sort order — that
-- is what the unique indexes on `people.name` and `roster_entries.ign` rely on.
CREATE COLLATION IF NOT EXISTS nocase (
    provider      = icu,
    locale        = 'und-u-ks-level2',
    deterministic = false
);

-- ---------------------------------------------------------------- shoots

CREATE TABLE shoots (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT    NOT NULL,
    source_path    TEXT    NOT NULL,
    status         TEXT    NOT NULL DEFAULT 'created',
    notes          TEXT,
    created_at     TEXT    NOT NULL,
    updated_at     TEXT    NOT NULL,
    stable_id      TEXT    DEFAULT gen_random_uuid()::text,
    library_id     TEXT    DEFAULT gen_random_uuid()::text,
    cloud_revision BIGINT  NOT NULL DEFAULT 0,
    tombstone      BIGINT  NOT NULL DEFAULT 0,
    is_reference   BIGINT  NOT NULL DEFAULT 0
);

CREATE INDEX idx_shoots_created ON shoots (created_at DESC);
CREATE UNIQUE INDEX idx_shoots_stable_id ON shoots (stable_id);

-- ---------------------------------------------------------------- people

CREATE TABLE people (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT COLLATE nocase  NOT NULL,
    team           TEXT,
    notes          TEXT,
    cover_face_id  BIGINT,
    created_at     TEXT    NOT NULL,
    updated_at     TEXT    NOT NULL,
    stable_id      TEXT    DEFAULT gen_random_uuid()::text,
    cloud_revision BIGINT  NOT NULL DEFAULT 0,
    tombstone      BIGINT  NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_people_name ON people (name);
CREATE INDEX idx_people_team ON people (team);
CREATE UNIQUE INDEX idx_people_stable_id ON people (stable_id);

-- ---------------------------------------------------------------- media

CREATE TABLE media (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id                 BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    path                     TEXT   NOT NULL,
    filename                 TEXT   NOT NULL,
    media_type               TEXT   NOT NULL,          -- photo | video
    extension                TEXT   NOT NULL,
    width                    BIGINT,
    height                   BIGINT,
    duration                 DOUBLE PRECISION,         -- seconds, videos only
    file_size                BIGINT NOT NULL DEFAULT 0,
    content_key              TEXT   NOT NULL,          -- blake3(path|size|mtime)
    captured_at              TEXT,                     -- EXIF capture time, else file mtime
    indexed_at               TEXT   NOT NULL,
    camera_make              TEXT,
    camera_model             TEXT,
    lens                     TEXT,
    iso                      BIGINT,
    focal_length             DOUBLE PRECISION,
    aperture                 DOUBLE PRECISION,
    shutter                  TEXT,
    orientation              BIGINT NOT NULL DEFAULT 1,
    thumbnail_path           TEXT,
    processing_status        TEXT   NOT NULL DEFAULT 'pending',
    face_count               BIGINT NOT NULL DEFAULT 0,
    error                    TEXT,
    person_count             BIGINT NOT NULL DEFAULT 0,
    quality_score            DOUBLE PRECISION,
    sharpness_score          DOUBLE PRECISION,
    exposure_score           DOUBLE PRECISION,
    perceptual_hash          TEXT,
    duplicate_group_id       BIGINT,
    duplicate_count          BIGINT NOT NULL DEFAULT 1,
    is_best_shot             BIGINT NOT NULL DEFAULT 0,
    rating                   BIGINT NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
    pick_state               TEXT   NOT NULL DEFAULT 'none'
                                    CHECK (pick_state IN ('none', 'pick', 'reject')),
    stable_id                TEXT   DEFAULT gen_random_uuid()::text,
    normalized_relative_path TEXT,
    fps                      DOUBLE PRECISION,
    bitrate                  BIGINT,
    video_codec              TEXT,
    audio_codec              TEXT,
    cloud_revision           BIGINT NOT NULL DEFAULT 0,
    tombstone                BIGINT NOT NULL DEFAULT 0,
    UNIQUE (shoot_id, path)
);

CREATE INDEX idx_media_shoot ON media (shoot_id, media_type);
CREATE INDEX idx_media_status ON media (shoot_id, processing_status);
CREATE INDEX idx_media_captured ON media (shoot_id, captured_at);
CREATE INDEX idx_media_person_count ON media (shoot_id, person_count);
CREATE INDEX idx_media_quality ON media (shoot_id, media_type, quality_score DESC);
CREATE INDEX idx_media_duplicates ON media (shoot_id, duplicate_group_id);
CREATE INDEX idx_media_editorial ON media (shoot_id, pick_state, rating DESC);
CREATE UNIQUE INDEX idx_media_stable_id ON media (stable_id);

-- ---------------------------------------------------------------- clusters

CREATE TABLE clusters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id      BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    label         TEXT   NOT NULL,                     -- "Unknown Person 1"
    person_id     BIGINT REFERENCES people (id) ON DELETE SET NULL,
    status        TEXT   NOT NULL DEFAULT 'unnamed',   -- unnamed | named | ignored
    face_count    BIGINT NOT NULL DEFAULT 0,
    cover_face_id BIGINT,
    created_at    TEXT   NOT NULL,
    stable_id     TEXT   DEFAULT gen_random_uuid()::text
);

CREATE INDEX idx_clusters_shoot ON clusters (shoot_id, status);
CREATE UNIQUE INDEX idx_clusters_stable_id ON clusters (stable_id);

-- ---------------------------------------------------------------- faces

CREATE TABLE faces (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id               BIGINT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    shoot_id               BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    person_id              BIGINT REFERENCES people (id) ON DELETE SET NULL,
    cluster_id             BIGINT REFERENCES clusters (id) ON DELETE SET NULL,
    embedding              BYTEA,                      -- little-endian f32[embedding_dim]
    embedding_dim          BIGINT,
    bbox_x                 DOUBLE PRECISION NOT NULL,  -- normalised 0..1 against the full frame
    bbox_y                 DOUBLE PRECISION NOT NULL,
    bbox_w                 DOUBLE PRECISION NOT NULL,
    bbox_h                 DOUBLE PRECISION NOT NULL,
    landmarks              BYTEA,                      -- little-endian f32[10] (5 points, pixel space)
    detection_confidence   DOUBLE PRECISION NOT NULL,
    recognition_confidence DOUBLE PRECISION,
    assignment             TEXT NOT NULL DEFAULT 'unassigned',
                                  -- unassigned | suggested | confirmed | rejected | ignored
    quality                DOUBLE PRECISION,
    frame_time             DOUBLE PRECISION,           -- seconds into the video the frame came from
    crop_path              TEXT,
    created_at             TEXT NOT NULL,
    source                 TEXT NOT NULL DEFAULT 'detected'
);

CREATE INDEX idx_faces_media ON faces (media_id);
CREATE INDEX idx_faces_person ON faces (person_id);
CREATE INDEX idx_faces_cluster ON faces (cluster_id);
CREATE INDEX idx_faces_shoot_assignment ON faces (shoot_id, assignment);
CREATE INDEX idx_faces_media_source ON faces (media_id, source);

-- ---------------------------------------------------------------- video

CREATE TABLE video_detections (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id      BIGINT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    person_id     BIGINT REFERENCES people (id) ON DELETE CASCADE,
    face_id       BIGINT REFERENCES faces (id) ON DELETE CASCADE,
    timestamp     DOUBLE PRECISION NOT NULL,
    end_timestamp DOUBLE PRECISION,
    confidence    DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_video_detections_media ON video_detections (media_id, timestamp);
CREATE INDEX idx_video_detections_person ON video_detections (person_id);

CREATE TABLE video_sample_frames (
    media_id   BIGINT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    timestamp  DOUBLE PRECISION NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (media_id, timestamp)
);

CREATE INDEX idx_video_sample_frames_media ON video_sample_frames (media_id, timestamp);

-- ---------------------------------------------------------------- albums

CREATE TABLE albums (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id       BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    name           TEXT   NOT NULL,
    album_type     TEXT   NOT NULL,             -- player | multi_player | unidentified | team
    person_ids     TEXT,                        -- JSON array of person ids
    cluster_id     BIGINT REFERENCES clusters (id) ON DELETE CASCADE,
    cover_media_id BIGINT REFERENCES media (id) ON DELETE SET NULL,
    media_count    BIGINT NOT NULL DEFAULT 0,
    photo_count    BIGINT NOT NULL DEFAULT 0,
    video_count    BIGINT NOT NULL DEFAULT 0,
    sort_order     BIGINT NOT NULL DEFAULT 0,
    generated_at   TEXT   NOT NULL,
    stable_id      TEXT   DEFAULT gen_random_uuid()::text,
    UNIQUE (shoot_id, album_type, name)
);

CREATE INDEX idx_albums_shoot ON albums (shoot_id, album_type, sort_order);
CREATE UNIQUE INDEX idx_albums_stable_id ON albums (stable_id);

CREATE TABLE album_media (
    album_id BIGINT NOT NULL REFERENCES albums (id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    PRIMARY KEY (album_id, media_id)
);

CREATE INDEX idx_album_media_media ON album_media (media_id);

-- ---------------------------------------------------------------- manual groups

CREATE TABLE media_groups (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id       BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    name           TEXT COLLATE nocase NOT NULL,
    -- NULL means "use `name`"; set when the editor wants the folder on disk to
    -- differ from the label they work with.
    folder_name    TEXT,
    notes          TEXT,
    -- Set when the group was seeded from an AI player album, so the UI can say
    -- where it came from. Clearing the player never removes the group.
    person_id      BIGINT REFERENCES people (id) ON DELETE SET NULL,
    sort_order     BIGINT NOT NULL DEFAULT 0,
    media_count    BIGINT NOT NULL DEFAULT 0,
    photo_count    BIGINT NOT NULL DEFAULT 0,
    video_count    BIGINT NOT NULL DEFAULT 0,
    cover_media_id BIGINT REFERENCES media (id) ON DELETE SET NULL,
    created_at     TEXT   NOT NULL,
    updated_at     TEXT   NOT NULL,
    stable_id      TEXT   DEFAULT gen_random_uuid()::text,
    UNIQUE (shoot_id, name)
);

CREATE INDEX idx_media_groups_shoot ON media_groups (shoot_id, sort_order, name);
CREATE UNIQUE INDEX idx_media_groups_stable_id ON media_groups (stable_id);

CREATE TABLE media_group_items (
    group_id BIGINT NOT NULL REFERENCES media_groups (id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    added_at TEXT   NOT NULL,
    PRIMARY KEY (group_id, media_id)
);

CREATE INDEX idx_media_group_items_media ON media_group_items (media_id);

-- ---------------------------------------------------------------- jobs & exports

CREATE TABLE jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id    BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    media_id    BIGINT REFERENCES media (id) ON DELETE CASCADE,
    kind        TEXT   NOT NULL,                       -- scan | thumbnail | analysePhoto | ...
    state       TEXT   NOT NULL DEFAULT 'queued',      -- queued | running | done | failed | cancelled
    priority    BIGINT NOT NULL DEFAULT 100,
    attempts    BIGINT NOT NULL DEFAULT 0,
    payload     TEXT,
    error       TEXT,
    created_at  TEXT   NOT NULL,
    started_at  TEXT,
    finished_at TEXT
);

CREATE INDEX idx_jobs_pick ON jobs (state, priority, id);
CREATE INDEX idx_jobs_shoot ON jobs (shoot_id, state);

CREATE TABLE exports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id    BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    destination TEXT   NOT NULL,
    options     TEXT   NOT NULL,                       -- JSON ExportOptions
    status      TEXT   NOT NULL DEFAULT 'queued',
    files_total BIGINT NOT NULL DEFAULT 0,
    files_done  BIGINT NOT NULL DEFAULT 0,
    bytes_done  BIGINT NOT NULL DEFAULT 0,
    error       TEXT,
    started_at  TEXT,
    finished_at TEXT
);

CREATE INDEX idx_exports_shoot ON exports (shoot_id, started_at DESC);

-- ---------------------------------------------------------------- settings & log

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Deliberately stores identifiers and outcomes only; never embeddings or crops.
CREATE TABLE app_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    event     TEXT NOT NULL,
    shoot_id  BIGINT,
    media_id  BIGINT,
    person_id BIGINT,
    detail    TEXT
);

CREATE INDEX idx_app_log_time ON app_log (timestamp DESC);
CREATE INDEX idx_app_log_event ON app_log (event, timestamp DESC);

-- ---------------------------------------------------------------- shared catalogue

CREATE TABLE library_mappings (
    library_id  TEXT PRIMARY KEY,
    label       TEXT NOT NULL,
    local_root  TEXT NOT NULL,
    approved_at TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);

CREATE TABLE sync_outbox (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id  TEXT   NOT NULL UNIQUE,
    workspace_id  TEXT   NOT NULL,
    entity_type   TEXT   NOT NULL,
    entity_id     TEXT   NOT NULL,
    operation     TEXT   NOT NULL,
    base_revision BIGINT NOT NULL,
    payload       TEXT   NOT NULL,
    created_at    TEXT   NOT NULL,
    attempted_at  TEXT,
    sent_at       TEXT,
    error         TEXT
);

CREATE INDEX idx_sync_outbox_pending ON sync_outbox (sent_at, id);

CREATE TABLE sync_conflicts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conflict_id    TEXT NOT NULL UNIQUE,
    workspace_id   TEXT NOT NULL,
    entity_type    TEXT NOT NULL,
    entity_id      TEXT NOT NULL,
    local_payload  TEXT NOT NULL,
    remote_payload TEXT NOT NULL,
    detected_at    TEXT NOT NULL,
    resolved_at    TEXT,
    resolution     TEXT
);

CREATE TABLE catalogue_revisions (
    revision_id     TEXT PRIMARY KEY,
    package_id      TEXT   NOT NULL,
    shoot_id        BIGINT REFERENCES shoots (id) ON DELETE SET NULL,
    revision_number BIGINT NOT NULL,
    state           TEXT   NOT NULL CHECK (state IN ('draft', 'published', 'applied', 'rolled_back')),
    object_key      TEXT,
    manifest_hash   TEXT,
    created_at      TEXT   NOT NULL,
    published_at    TEXT,
    applied_at      TEXT,
    UNIQUE (package_id, revision_number)
);

CREATE TABLE imported_catalogues (
    package_id     TEXT NOT NULL,
    revision_id    TEXT NOT NULL,
    library_id     TEXT NOT NULL,
    shoot_id       TEXT NOT NULL,
    catalogue_hash TEXT NOT NULL,
    imported_at    TEXT NOT NULL,
    PRIMARY KEY (package_id, revision_id)
);

-- ---------------------------------------------------------------- telemetry

CREATE TABLE processing_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shoot_id          BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    status            TEXT NOT NULL DEFAULT 'running'
                      CHECK (status IN ('running', 'completed', 'failed', 'cancelled')),
    started_at        TEXT NOT NULL,
    scan_completed_at TEXT,
    completed_at      TEXT,
    cpu_metric_scope  TEXT NOT NULL DEFAULT 'process'
);

-- At most one unfinished attempt per shoot. This also makes simultaneous
-- workers racing to start the first file safe.
CREATE UNIQUE INDEX idx_processing_runs_active
    ON processing_runs (shoot_id) WHERE status = 'running';
CREATE INDEX idx_processing_runs_shoot_started
    ON processing_runs (shoot_id, started_at DESC);

CREATE TABLE processing_stage_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processing_run_id BIGINT NOT NULL REFERENCES processing_runs (id) ON DELETE CASCADE,
    stage             TEXT NOT NULL,
    started_at        TEXT NOT NULL,
    completed_at      TEXT,
    UNIQUE (processing_run_id, stage)
);

CREATE TABLE processing_resource_samples (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processing_run_id BIGINT NOT NULL REFERENCES processing_runs (id) ON DELETE CASCADE,
    recorded_at       TEXT   NOT NULL,
    elapsed_ms        BIGINT NOT NULL,
    cpu_percent       DOUBLE PRECISION,
    gpu_percent       DOUBLE PRECISION,
    active_workers    BIGINT NOT NULL DEFAULT 0,
    concurrent_shoots BIGINT NOT NULL DEFAULT 1
);

CREATE INDEX idx_processing_samples_run_time
    ON processing_resource_samples (processing_run_id, elapsed_ms);

-- ---------------------------------------------------------------- projects

CREATE TABLE projects (
    id               TEXT PRIMARY KEY,
    owner_account_id TEXT   NOT NULL,
    owner_email      TEXT   NOT NULL,
    organisation     TEXT,
    name             TEXT   NOT NULL,
    kind             TEXT   NOT NULL,
    visibility       TEXT   NOT NULL DEFAULT 'private'
                     CHECK (visibility IN ('private', 'invited', 'organisation')),
    status           TEXT   NOT NULL DEFAULT 'active'
                     CHECK (status IN ('active', 'archived')),
    cover_media_id   BIGINT REFERENCES media (id) ON DELETE SET NULL,
    created_at       TEXT   NOT NULL,
    updated_at       TEXT   NOT NULL
);

CREATE INDEX idx_projects_owner ON projects (owner_account_id, status, updated_at DESC);
CREATE INDEX idx_projects_visibility ON projects (visibility, status, updated_at DESC);

CREATE TABLE project_members (
    project_id       TEXT   NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    email            TEXT COLLATE nocase NOT NULL,
    display_name     TEXT,
    role             TEXT   NOT NULL CHECK (role IN ('editor', 'viewer')),
    invitation_state TEXT   NOT NULL DEFAULT 'invited'
                     CHECK (invitation_state IN ('invited', 'accepted')),
    created_at       TEXT   NOT NULL,
    PRIMARY KEY (project_id, email)
);

CREATE INDEX idx_project_members_email ON project_members (email);

CREATE TABLE project_collections (
    id         TEXT   PRIMARY KEY,
    project_id TEXT   NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    parent_id  TEXT   REFERENCES project_collections (id) ON DELETE CASCADE,
    name       TEXT COLLATE nocase NOT NULL,
    notes      TEXT,
    sort_order BIGINT NOT NULL DEFAULT 0,
    created_at TEXT   NOT NULL,
    updated_at TEXT   NOT NULL
);

CREATE INDEX idx_project_collections_parent
    ON project_collections (project_id, parent_id, sort_order, name);
CREATE UNIQUE INDEX idx_project_collections_name
    ON project_collections (project_id, COALESCE(parent_id, ''), name);

CREATE TABLE project_collection_sources (
    collection_id TEXT   NOT NULL REFERENCES project_collections (id) ON DELETE CASCADE,
    shoot_id      BIGINT NOT NULL REFERENCES shoots (id) ON DELETE CASCADE,
    group_id      BIGINT NOT NULL REFERENCES media_groups (id) ON DELETE CASCADE,
    added_at      TEXT   NOT NULL,
    PRIMARY KEY (collection_id, shoot_id, group_id)
);

-- ---------------------------------------------------------------- roster

CREATE TABLE roster_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The in-game name. Unique across the workspace: it is what a reviewer
    -- types and what identifies a player on the broadcast.
    ign         TEXT COLLATE nocase NOT NULL,
    -- The person behind the IGN. Optional; some rosters only carry IGNs.
    player_name TEXT   NOT NULL DEFAULT '',
    team        TEXT COLLATE nocase NOT NULL,
    -- player, coach, analyst, staff, substitute... Anything not a player can be
    -- excluded from team collections without being lost.
    role        TEXT   NOT NULL DEFAULT 'player',
    -- Lowercased letters and digits of the IGN, player name and team joined
    -- together, so "S8UL Naresh", "s8ulnaresh" and "naresh" all match the same
    -- row without the caller worrying about spaces, dots or case.
    search_key  TEXT   NOT NULL,
    -- The file this row was imported from, so one roster can be replaced
    -- without disturbing another.
    source      TEXT   NOT NULL DEFAULT '',
    imported_at TEXT   NOT NULL
);

CREATE UNIQUE INDEX idx_roster_entries_ign ON roster_entries (ign);
CREATE INDEX idx_roster_entries_team ON roster_entries (team);
CREATE INDEX idx_roster_entries_search ON roster_entries (search_key);
