-- Taxonomy: named tags, the values each has been given, and where they apply.
--
-- A tag is a name ("Team", "Venue", "Sponsor") and every value it has ever
-- been recorded with. Values are kept per tag rather than free text on the
-- asset so that typing "Gods" anywhere a tag is entered can offer "Gods
-- Reign" — the taxonomy is the list of what the studio has already said.
--
-- Assignments are polymorphic: a media row, an automatic group, a face
-- cluster or a project collection can each carry any number of values,
-- including several values of one tag. Keys are text because the assets
-- differ in id type (collections are UUIDs) and because automatic groups are
-- regenerated with new ids and are addressed by what they *are* instead.

CREATE TABLE tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT COLLATE nocase NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE tag_values (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id     BIGINT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
    value      TEXT COLLATE nocase NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (tag_id, value)
);

CREATE INDEX idx_tag_values_tag ON tag_values (tag_id, value);

CREATE TABLE asset_tags (
    tag_value_id BIGINT NOT NULL REFERENCES tag_values (id) ON DELETE CASCADE,
    -- media | album | cluster | collection
    asset_kind   TEXT   NOT NULL,
    asset_key    TEXT   NOT NULL,
    created_at   TEXT   NOT NULL,
    PRIMARY KEY (tag_value_id, asset_kind, asset_key)
);

CREATE INDEX idx_asset_tags_asset ON asset_tags (asset_kind, asset_key);
