//! Where the backend's secrets come from.
//!
//! The service holds the organisation's signing key, so this is the most
//! sensitive configuration in the product. Two sources, in order:
//!
//!   1. **The process environment**, which is what a developer running
//!      `cargo run -p skwad-backend` uses and what CI sets. Unchanged from
//!      before; nothing about running as a service alters it.
//!   2. **A config file**, because a Windows service does not inherit anybody's
//!      shell environment — it is started by the Service Control Manager with a
//!      bare environment block. Without this the service would start, fail
//!      `required()`, and exit 2 on every boot.
//!
//! Environment wins per-variable, so a developer can override one value against
//! an installed service's file without editing it.
//!
//! The file is deliberately *not* in the repository or the library folder. It
//! lives beside the machine's other service state (`%PROGRAMDATA%\SKWAD` on
//! Windows, `/etc/skwad` elsewhere) with an ACL that excludes ordinary users —
//! see `install`, which writes it.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Overrides where the config file is read from. Mainly for tests and for
/// running two backends on one machine.
pub const CONFIG_PATH_VAR: &str = "SKWAD_BACKEND_CONFIG";

/// Every secret the service needs, in the order `keygen` prints them.
pub const REQUIRED_VARS: &[&str] = &[
    "SKWAD_BACKEND_AUTH_TOKEN",
    "SKWAD_SIGNING_KEY_ID",
    "SKWAD_SIGNING_PRIVATE_KEY",
    "SKWAD_WRAPPING_KEY_ID",
    "SKWAD_WRAPPING_PRIVATE_KEY",
    "SKWAD_WRAPPING_PUBLIC_KEY",
];

/// The default config file for this machine.
pub fn default_config_path() -> PathBuf {
    if let Some(explicit) = std::env::var_os(CONFIG_PATH_VAR) {
        return PathBuf::from(explicit);
    }
    #[cfg(windows)]
    {
        let root = std::env::var_os("PROGRAMDATA").unwrap_or_else(|| r"C:\ProgramData".into());
        PathBuf::from(root).join("SKWAD").join("backend.env")
    }
    #[cfg(not(windows))]
    {
        PathBuf::from("/etc/skwad/backend.env")
    }
}

/// Where the service writes its log, since it has no console.
pub fn default_log_dir() -> PathBuf {
    #[cfg(windows)]
    {
        let root = std::env::var_os("PROGRAMDATA").unwrap_or_else(|| r"C:\ProgramData".into());
        PathBuf::from(root).join("SKWAD").join("logs")
    }
    #[cfg(not(windows))]
    {
        PathBuf::from("/var/log/skwad")
    }
}

/// Parses `KEY=VALUE` lines, ignoring blanks and `#` comments.
///
/// Values are taken verbatim to the end of the line — these are base64 secrets,
/// so there is no quoting or escaping to get wrong, and a stray quote would
/// silently corrupt a key rather than fail loudly.
pub fn parse(contents: &str) -> HashMap<String, String> {
    contents
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .filter_map(|line| line.split_once('='))
        .map(|(key, value)| (key.trim().to_string(), value.trim().to_string()))
        .collect()
}

/// Reads `name` from the environment, falling back to the config file.
///
/// The file is read once and cached, so a missing file costs one failed open
/// rather than one per variable.
pub struct Source {
    file: HashMap<String, String>,
    path: PathBuf,
    loaded: bool,
}

impl Source {
    pub fn discover() -> Self {
        let path = default_config_path();
        match std::fs::read_to_string(&path) {
            Ok(contents) => Self {
                file: parse(&contents),
                path,
                loaded: true,
            },
            Err(_) => Self {
                file: HashMap::new(),
                path,
                loaded: false,
            },
        }
    }

    pub fn get(&self, name: &str) -> Option<String> {
        std::env::var(name).ok().or_else(|| self.file.get(name).cloned())
    }

    /// The file this would have read, for error messages.
    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn file_was_read(&self) -> bool {
        self.loaded
    }
}

/// Renders a config file from the values `keygen` produced.
pub fn render(values: &[(String, String)]) -> String {
    let mut out = String::from(
        "# SKWAD backend secrets. Generated by `skwad-backend install`.\n\
         #\n\
         # This file holds the organisation's signing key. Anyone who can read it\n\
         # can sign catalogues as this organisation. It is ACL'd to SYSTEM,\n\
         # Administrators and the service account only; keep it that way, and keep\n\
         # it out of version control and backups that others can read.\n\
         #\n\
         # A matching environment variable overrides any line here.\n\n",
    );
    for (key, value) in values {
        out.push_str(key);
        out.push('=');
        out.push_str(value);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_pairs_and_ignores_noise() {
        let parsed = parse(
            "# a comment\n\
             \n\
             SKWAD_SIGNING_KEY_ID=local-signing-v1\n\
             SKWAD_BACKEND_AUTH_TOKEN =  spaces-are-trimmed  \n\
             not a pair\n",
        );
        assert_eq!(parsed.get("SKWAD_SIGNING_KEY_ID").unwrap(), "local-signing-v1");
        assert_eq!(parsed.get("SKWAD_BACKEND_AUTH_TOKEN").unwrap(), "spaces-are-trimmed");
        assert_eq!(parsed.len(), 2, "comments, blanks and non-pairs are skipped");
    }

    /// Base64 secrets end in `=` padding, which a naive `split('=')` would eat.
    #[test]
    fn a_value_may_contain_equals_signs() {
        let parsed = parse("SKWAD_SIGNING_PRIVATE_KEY=YWJjZGVm==\n");
        assert_eq!(parsed.get("SKWAD_SIGNING_PRIVATE_KEY").unwrap(), "YWJjZGVm==");
    }

    #[test]
    fn a_rendered_file_round_trips() {
        let values: Vec<(String, String)> = REQUIRED_VARS
            .iter()
            .map(|name| (name.to_string(), format!("value-for-{name}")))
            .collect();
        let parsed = parse(&render(&values));
        for name in REQUIRED_VARS {
            assert_eq!(parsed.get(*name).unwrap(), &format!("value-for-{name}"));
        }
    }
}
